name: Devweek

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    env:
      CAMINHO_PROJETO_TESTS: ./APITemperatura.Especificacoes/APITemperatura.Especificacoes.csproj
      CAMINHO_PROJETO_WEBAPP: ./APITemperatura
      NOME_IMAGEM: apidevweek
      NOME_COMPLETO_IMAGEM: ${{ secrets.CONTAINER_REGISTRY }}/$NOME_IMAGEM
      NOME_WEBAPP: apidevweek

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
        
    - name: Listas versoes do .NET
      run:  dotnet --list-sdks
        
    - name: Executar testes automatizados
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTS }} --verbosity minimal
      
    - name: Login no Azure Container Registry
      uses: docker/login-action@v1.6.0
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
  
    - name: Build e Push no Azure Container Registry
      run: |
        cd ${{ env.CAMINHO_PROJETO_WEBAPP }}
        docker build . --file Dockerfile --tag ${{ env.NOME_COMPLETO_IMAGEM }}:latest
        docker tag ${{ env.NOME_COMPLETO_IMAGEM }}:latest ${{ env.NOME_COMPLETO_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.NOME_COMPLETO_IMAGEM }}

    - name: Azure Login - Conectando com Credenciais no Azure
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure WebApp - Deployment da Aplicacao - Containers
      uses: Azure/webapps-deploy/@v2
      with:
        app-name: ${{ env.NOME_WEBAPP }}
        images: 'leohicksteingithubactions.azurecr.io/apidevweek:${{ github.run_number }}'
        #images: '${{ NOME_COMPLETO_IMAGEM }}:${{ github.run_number }}'
        
#    - name: Build com utilitario dotnet
#      run: dotnet build ${{ env.CAMINHO_PROJETO_WEBAPP }} --configuration Release
      
#    - name: Publish com o utilitario dotnet
#      run: dotnet publish ${{ env.CAMINHO_PROJETO_WEBAPP }} --c Release -o app
      
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
